# Generated by Django 5.2.6 on 2025-09-06 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], default='D', max_length=1)),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_as_base', to='core.currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_as_quote', to='core.currency')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exchangesource')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['base', 'quote', 'date', 'timeframe'], name='rates_excha_base_id_efc8ef_idx')],
                'unique_together': {('source', 'base', 'quote', 'timeframe', 'date')},
            },
        ),
    ]
