# Generated by Django 5.2.6 on 2025-09-06 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Currency code must be a 3-letter ISO uppercase code (e.g., USD).', regex='^[A-Z]{3}$')])),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, default='', max_length=8)),
                ('decimals', models.PositiveSmallIntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('base_url', models.URLField(blank=True, default='')),
            ],
        ),
    ]
