# Generated by Django 5.2.6 on 2025-09-06 15:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of', models.DateTimeField()),
                ('timeframe', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], default='D', max_length=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('trigger', models.CharField(blank=True, default='manual', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fx_forecast_run',
                'ordering': ['-as_of'],
            },
        ),
        migrations.CreateModel(
            name='ModelSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('library', models.CharField(choices=[('arima', 'ARIMA/SARIMAX'), ('prophet', 'Prophet'), ('lstm', 'LSTM'), ('xgb', 'XGBoost')], max_length=16)),
                ('timeframe', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], default='D', max_length=1)),
                ('horizon_days', models.PositiveSmallIntegerField(default=1)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fx_model_spec',
                'indexes': [models.Index(fields=['library', 'timeframe', 'active'], name='fx_model_sp_library_a0ed82_idx')],
            },
        ),
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timeframe', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], default='D', max_length=1)),
                ('horizon_days', models.PositiveSmallIntegerField(default=1)),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forecasting.modelspec')),
            ],
            options={
                'db_table': 'fx_backtest_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mape', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('n', models.PositiveIntegerField(default=0)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bt_metrics_as_base', to='core.currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bt_metrics_as_quote', to='core.currency')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='forecasting.backtestrun')),
            ],
            options={
                'db_table': 'fx_backtest_metric',
                'indexes': [models.Index(fields=['quote'], name='fx_backtest_quote_i_acde6f_idx')],
                'unique_together': {('run', 'base', 'quote')},
            },
        ),
        migrations.CreateModel(
            name='BacktestSlice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('actual', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('forecast', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bt_as_base', to='core.currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bt_as_quote', to='core.currency')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slices', to='forecasting.backtestrun')),
            ],
            options={
                'db_table': 'fx_backtest_slice',
                'indexes': [models.Index(fields=['quote', 'date'], name='fx_backtest_quote_i_d93f3a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('actual__gt', 0)), name='fx_bt_actual_positive'), models.CheckConstraint(condition=models.Q(('forecast__gt', 0)), name='fx_bt_forecast_positive')],
                'unique_together': {('run', 'base', 'quote', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('yhat', models.DecimalField(decimal_places=8, max_digits=20)),
                ('yhat_lower', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('yhat_upper', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('extras', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts_as_base', to='core.currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts_as_quote', to='core.currency')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='forecasting.forecastrun')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forecasting.modelspec')),
            ],
            options={
                'db_table': 'fx_forecast',
                'ordering': ['target_date', 'base__code', 'quote__code'],
                'indexes': [models.Index(fields=['quote', 'target_date'], name='fx_forecast_quote_i_67aca4_idx'), models.Index(fields=['model', 'target_date'], name='fx_forecast_model_i_ec7b76_idx'), models.Index(fields=['run'], name='fx_forecast_run_id_30325f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('yhat__gt', 0)), name='fx_forecast_yhat_positive')],
                'unique_together': {('run', 'model', 'base', 'quote', 'target_date')},
            },
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['model', 'timeframe'], name='fx_backtest_model_i_2c4444_idx'),
        ),
    ]
