# Generated by Django 5.2.6 on 2025-09-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastrun',
            name='data_cutoff_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='model_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='modelspec',
            name='library',
            field=models.CharField(choices=[('baseline', 'Baseline'), ('arima', 'ARIMA/SARIMAX'), ('prophet', 'Prophet'), ('lstm', 'LSTM'), ('xgb', 'XGBoost')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='forecastrun',
            constraint=models.UniqueConstraint(condition=models.Q(('model_name', ''), _negated=True), fields=('timeframe', 'data_cutoff_date', 'model_name'), name='fx_run_unique_tf_cutoff_model'),
        ),
    ]
