# Generated by Django 5.2.6 on 2025-12-14 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssession',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='analyticssession',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='analyticssession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyticssession',
            name='region',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
